//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDBLocalMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int Id { get; set; }
        [Required()]
        [Display(Name = "Nombre Cliente")]
        [MaxLength (200)]
        public string Nombre { get; set; }
        [Required()]
        [Display(Name = "Apellido Cliente")]
        [MaxLength(200)]
        public string Apellido { get; set; }

        [Display(Name = "Email")]
        [DataType (DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Identificacion")]
        [DataType(DataType.CreditCard)]
        [MaxLength(10)]
        public string Identificacion { get; set; }
    
        public virtual ICollection<Cuenta> Cuenta { get; set; }
    }
}
