//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDBLocalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual PlanCelular PlanCelular { get; set; }
    }
}
